// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorPagesShowSearcher.Data;

namespace RazorPagesShowSearcher.Migrations
{
    [DbContext(typeof(RazorPagesShowSearcherContext))]
    [Migration("20191027033425_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RazorPagesShowSearcher.Models.Show", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Genra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumOfSeasons")
                        .HasColumnType("int");

                    b.Property<string>("OriginalNetwork")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShowDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShowName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ShowRate")
                        .HasColumnType("float");

                    b.Property<string>("ShowTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearShowBegan")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Show");
                });
#pragma warning restore 612, 618
        }
    }
}
